(deftheme cemant "Grayish lightish color scheme for Emacs")

(let* ((c-w  "#bbbbc3")
       (c-r  "#a92636")
       (c-g  "#437e00")
       (c-y  "#8b6b02")
       (c-b  "#4051b0")
       (c-m  "#9a1e98")
       (c-c  "#007f68")
       (c-d  "#5a595f")
       (c-l  "#95959d")
       (c-rr "#c74032")
       (c-gg "#23920e")
       (c-yy "#947c27")
       (c-bb "#1c75af")
       (c-mm "#8228c0")
       (c-cc "#4a8798")
       (c-k  "#3a393f")
       (c-1  c-k)
       (c-2  c-b)
       (c-3  c-c)
       (c-4  c-g)
       (c-5  c-y)
       (c-6  c-r)
       (c-7  c-m)
       (c-8  c-d)
       (c-9  c-bb)
       (c-10 c-cc)
       (c-11 c-gg)
       (c-12 c-yy)
       (c-13 c-rr)
       (c-14 c-mm)
       (c-15 "#ababb3")
       (c-16 "#b0b0b8")
       (c-bg c-w)
       (c-fg c-k))

  (custom-theme-set-faces
   'cemant

   `(default              ((t (:background ,c-bg :foreground ,c-fg))))
   `(button               ((t (:foreground ,c-m  :underline t))))
   `(cursor               ((t (:background ,c-k))))
   `(fringe               ((t (:background ,c-w))))
   `(header-line          ((t (:background ,c-b  :foreground ,c-fg))))
   `(highlight            ((t (:background ,c-15))))
   `(highlight-face       ((t (:background ,c-15))))
   `(hl-line              ((t (:background ,c-15))))
   `(info-xref            ((t (:foreground ,c-g  :underline t))))
   `(linum                ((t (:background ,c-16 :foreground ,c-d))))
   `(linum-highlight-face ((t (:background ,c-l  :foreground ,c-k :weight bold))))
   `(mode-line            ((t (:background ,c-k  :foreground ,c-w))))
   `(mode-line-inactive   ((t (:background ,c-l  :foreground ,c-d))))
   `(region               ((t (:background ,c-l))))
   `(vertical-border      ((t (:foreground ,c-l))))

   `(font-lock-builtin-face           ((t (:foreground ,c-y))))
   `(font-lock-comment-face           ((t (:foreground ,c-b))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,c-b))))
   `(font-lock-constant-face          ((t (:foreground ,c-r))))
   `(font-lock-doc-face               ((t (:foreground ,c-rr))))
   `(font-lock-doc-string-face        ((t (:foreground ,c-rr))))
   `(font-lock-function-name-face     ((t (:foreground ,c-k))))
   `(font-lock-keyword-face           ((t (:foreground ,c-y))))
   `(font-lock-negation-char-face     ((t (:foreground ,c-mm))))
   `(font-lock-number-face            ((t (:foreground ,c-r))))
   `(font-lock-preprocessor-face      ((t (:foreground ,c-m))))
   `(font-lock-reference-face         ((t (:foreground ,c-r))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,c-r))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,c-r))))
   `(font-lock-string-face            ((t (:foreground ,c-r))))
   `(font-lock-type-face              ((t (:foreground ,c-g))))
   `(font-lock-variable-name-face     ((t (:foreground ,c-c))))
   `(font-lock-warning-face           ((t (:background ,c-r :foreground ,c-w))))

   `(org-agenda-structure ((t (:background ,c-bg :foreground ,c-fg :box (:line-width 2 :color ,c-w)))))
   `(org-document-title   ((t (:foreground ,c-d))))

   `(rainbow-delimiters-depth-1-face ((t (:foreground ,c-1))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,c-2))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,c-3))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,c-4))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,c-5))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,c-6))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,c-7))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,c-8))))

  ))

(provide-theme 'cemant)
